
const TelegramBot = require('node-telegram-bot-api');


const token = process.env.IMGJOURNEYBOT;
const bot = new TelegramBot(token);
const botlogger = "-1002195290478";

// https://api.telegram.org/bot<token>/setWebhook?url=<url>
// https://api.telegram.org/bot6986240990:AAEoRSLeGcIR5lvn2lHj7O4w3eXrqCJwvdE/setWebhook?url=https://b2c9-2409-40e4-22-96e4-3c88-b55a-dbc0-e5a2.ngrok-free.app/imgjourney
export const POST = async (req, res, next) => {

    console.log("starting");
    let data = await req.json();
    console.log("data");

    console.log("data",data);
    try {
        let manychat = fetch("https://wh.manychat.com/tgwh/tg0o83f4yg73hfgi73f2g89938g/7337693933/ff891aae85c41eebdf43f3c2b82615db3093162b",{
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data)
        })
    } catch (error) {
        console.log(error);
        
    }
   


    console.log("data2",data);
    
    let message = data?.edited_message || data?.message || data?.channel_post;
    console.log("message",message);
    const chatId = message.chat.id;
    console.log("chatId",chatId);
    const textContent = message.text || (message.caption ? message.caption : '');
    
    if (textContent === 'hi') {
        bot.sendMessage(chatId, 'Hello!');
    } else if(textContent == "/start"){
        bot.sendMessage(chatId, "🌟 Welcome to @ImgJourneyBot! 🌟\n\nI'm here to create magical images using prompts. Just send me a prompt, and I'll craft a unique image based on it. Let's embark on an image journey together! 🖼️\n\nJoin @SopBots to request new features or suggest new bots. We're always eager to hear from you! 🚀");
    } else {
        let loaderMessage  = await bot.sendMessage(chatId, 'Processing your Image...');
        bot.sendChatAction(chatId, 'typing');

        fetch("https://ask-me-api.vercel.app/api/nft", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ content: textContent })
            })
            .then(response => response.json())
            .then(data => {
                const base64Data = data.nft_image; 
                console.log(data);
                const imageData = Buffer.from(base64Data, 'base64');
                let captionText = 'Here is your image! generated by @imgjourneybot\nFrom Prompt :- <a href="#" onclick="document.execCommand(\'copy\'); return false;">'+textContent+'</a> \nJoin @sopbots Share your creation on @sopbotschat and Regenerate  /'+textContent.replaceAll(" ","_")+'' ;
                bot.sendPhoto(chatId, imageData, { caption: captionText, parse_mode: 'HTML', reply_markup: { inline_keyboard: [[{ text: 'Regenerate', callback_data: 'regenerate' }]] } }).then(() => {
                    bot.deleteMessage(chatId, loaderMessage.message_id);
                });
                bot.sendPhoto(botlogger, imageData, { caption: captionText, parse_mode: 'HTML', reply_markup: { inline_keyboard: [[{ text: 'Regenerate', callback_data: 'regenerate' }]] } }).then(() => {
                    // bot.deleteMessage(chatId, loaderMessage.message_id);
                });
                // bot.sendPhoto(chatId, imageData).then(() => {
                //     // Image sent, so we can hide the loading message
                //     bot.sendMessage(chatId, 'Request processed.');
                // }).catch(error => {
                //     console.error('Error sending image:', error);
                // });
            })
            .catch(error => {
                console.error('Error:', error);
                bot.sendMessage(chatId, 'An error occurred while processing your request');
            });
        // bot.sendMessage(chatId, 'Sorry, I only respond to "hi".');
    }
    
    return Response.json({
        message: 'Message sent successfully'
    });
}







export const GET = async (req, res, next) => {
    console.log(req);
    return Response.json({
        
    })
}